-- SQL Script for Online Bank Management System

-- Users Table
CREATE TABLE BMS_GTM_Users (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('CUSTOMER', 'EMPLOYEE', 'ADMIN')) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Accounts Table
CREATE TABLE BMS_GTM_Accounts (
    account_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    account_type VARCHAR2(20) CHECK (account_type IN ('SAVINGS', 'CURRENT')) NOT NULL,
    balance NUMBER(15, 2) DEFAULT 0.00 CHECK (balance >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES BMS_GTM_Users(user_id) ON DELETE CASCADE
);

-- Transactions Table
CREATE TABLE BMS_GTM_Transactions (
    transaction_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    account_id NUMBER NOT NULL,
    transaction_type VARCHAR2(20) CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')) NOT NULL,
    amount NUMBER(15, 2) CHECK (amount > 0) NOT NULL,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    beneficiary_account_id NUMBER,
    FOREIGN KEY (account_id) REFERENCES BMS_GTM_Accounts(account_id) ON DELETE CASCADE,
    FOREIGN KEY (beneficiary_account_id) REFERENCES BMS_GTM_Accounts(account_id)
);

-- Beneficiaries Table
CREATE TABLE BMS_GTM_Beneficiaries (
    beneficiary_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    beneficiary_account_id NUMBER NOT NULL,
    nickname VARCHAR2(50),
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES BMS_GTM_Users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (beneficiary_account_id) REFERENCES BMS_GTM_Accounts(account_id) ON DELETE CASCADE
);

-- Sample Data for Roles
INSERT INTO BMS_GTM_Users (username, password, email, role) VALUES ('admin', 'admin123', 'admin@bank.com', 'ADMIN');
INSERT INTO BMS_GTM_Users (username, password, email, role) VALUES ('employee', 'employee123', 'employee@bank.com', 'EMPLOYEE');
INSERT INTO BMS_GTM_Users (username, password, email, role) VALUES ('customer1', 'customer123', 'customer1@bank.com', 'CUSTOMER');
